blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/refract-org/refract/discussions
    about: Please use GitHub Discussions for how-to questions and ideas
